Dev 20200224 sui
capitalonline/flexvolume pull request #6
Opened 2020-03-02 11:27 UTC by yichuankaorou

修改了 nfs v3 和 v4 处理逻辑，测试通过

2020-03-02 11:47 UTC, tifayuki requested changes

2020-03-02 11:47 UTC, tifayuki commented on provider/nas/nas.go
> +		return errors.New("NAS: Path should start with /nfsshare, %s: " + opt.Path)
format string is not supported, in `errors.New()`.  should use `+` as before, or use `fmt.Errorf()` instead

2020-03-02 12:48 UTC, 970603878 reviewed
good job

2020-03-03 08:40 UTC, yichuankaorou reviewed
修改完成

2020-03-03 08:48 UTC, tifayuki approved these changes

2020-03-03 08:49 UTC, merged